### ISSUE TITLE
Id meaning

### ISSUE THREAD

**Issue by rezpe** [martgnz/madrid-atlas#1]
Hi,

Where can we find the table which links id and name. For example if I look at the neighbourhoods, I see the following object:
```javascript
madrid.objects.neighborhoods[0]
>> {
  type: "Polygon"
  id: "014"
  arcs: ▸Array(1) [Array(21)]
}
```

Where can the description of id 014 be found ?

Thanks,
Sebas

**Comment by LuisSevillano** [comment]
Hi @rezpe 

That id which are you referring is the concatenation of the district id and the neighborhood id.
- The district id's are treated as Strings, with zero-padding.
- The neighborhood ids are treated as numbers, with no zero-padding (these ids are repeated in each district):

Codigo de barrio | Codigo de distrito al que pertenece | Nombre de barrio | Nombre acentuado del barrio | Superficie (m2) | Perimetro (m) | id
-- | -- | -- | -- | -- | -- | --
1 | 01 | PALACIO | PALACIO | 1471085 | 5754 | 011
2 | 01 | EMBAJADORES | EMBAJADORES | 1032822 | 4267 | 012
3 | 01 | CORTES | CORTES | 592070 | 3731 | 013
4 | 01 | JUSTICIA | JUSTICIA | 742034 | 3598 | 014

(_the **id** field doesn't exist in the original dataset_).

The data sets **Distritos y barrios (información de perímetro, superficie y geográfica)** can be downloaded at the [Portal of open data of the city council of Madrid](https://datos.madrid.es/portal/site/egob/menuitem.c05c1f754a33a9fbe4b2e4b284f1a5a0/?vgnextoid=46b55cde99be2410VgnVCM1000000b205a0aRCRD&vgnextchannel=374512b9ace9f310VgnVCM100000171f5a0aRCRD). 

The first item listed refers to neighborhoods and the second one to districts.

**Comment by rezpe** [comment]
Thanks a lot !!!
